load("//nfpm:defs.bzl", "nfpm_package")

filegroup(
    name = "text-files",
    srcs = glob([
        "*.txt",
    ]),
)

nfpm_package(
    name = "test.rpm",
    config = "test-config.yaml",
    deps = [":text-files"],
    arch = "dummy-arch",
    envs = {
        "foo":"bar",
        "testpath": "$(rootpaths :text-files)",
    }
)

nfpm_package(
    name = "test.deb",
    config = "test-config.yaml",
    deps = [":text-files"],
    envs = {
        "foo":"bar",
        "testpath": "$(rootpaths :text-files)",
    }
)
